[package]
name = "ecdh"
version = "0.2.0"
authors = ["WalrusCow <willgmcd@gmail.com>"]

[dependencies]
rand = "0.3"
crypto_int = { git = "ssh://git@gitlab.com/walruscow/crypto-int.git" }
sha = { git = "ssh://git@gitlab.com/walruscow/sha.git" }
