[package]
name = "ecdh"
version = "0.3.1"
authors = ["WalrusCow <willgmcd@gmail.com>"]

[dependencies]
rand = "0.3"
crypto_int = { git = "https://github.com/walruscow/crypto_int.git" }
sha = { git = "https://github.com/walruscow/sha_rust.git" }
